### ISSUE TITLE
not showing the first data in the cell.

### ISSUE THREAD

**Issue by ajumalebrahim** [ArpitLokwani/ALCollapsableTableView#1]
Hi , i am recently need use an expandable/ collapse cell , and i found your code. I found a bug , the cell with the first data in array is missing. It just simply skip the first object from the array.

**Comment by ArpitLokwani** [comment]
Can you please elaborate the issues ? you are saying for section array or table cell array ?

**Comment by gavla** [comment]
I seem to have the same issue, when we create the indexpath.section instead of index path.row in cellForRowAtIndexPath: it seems to skip object 0 in the array for the tableview, I can add it in the else statement for your normal cell but with no expandable capabilities, I've tried removing the normal cell with no gain, would it be possible to post an example with no normal cell and all expanding cells/sections as I can't see where i'm loosing object 0

Edit i have found 2 work arounds if you remove the this if statement every time it comes up

```
    if ([self tableView:tableView canCollapseSection:indexPath.section])
```

or if you set the below method to -1

```
    - (BOOL)tableView:(UITableView *)tableView canCollapseSection:(NSInteger)section
     {
      if (section>-1) return YES;
      return NO;
       }
```

then all your sections from your array will be present but if anyone has a less bodged way please share with the class :)

**Comment by ArpitLokwani** [comment]
Yeah , that was not a bug , That i had given one normal non expandable cell :)

@gavis - you are correct with your effort or you can do something that 
- (BOOL)tableView:(UITableView *)tableView canCollapseSection:(NSInteger)section
  {
      return YES;

}
